from email import message


user_id = "user_id"
session_id = "session_id"
SESSION_ID = "Session-Id"
_id = "_id"
did = "id"
email = "email"
email_verified = "email_verified"
password_hash = "password_hash"
password_token_expiry = "password_token_expiry"
is_active = "is_active"
expireAt = "expireAt"
expiry_date = "expiry_date"
password = "password"
message = "message"
success = "success"
verification_token = "verification_token"
password_token = "password_token"